/**
 * FileExplorer — workspace file browser panel
 * Shows files generated by AI, supports navigation and download.
 */
import { useState, useEffect, useCallback } from "react";
import {
  Folder,
  FolderOpen,
  FileText,
  FileCode,
  FileImage,
  File,
  Download,
  ChevronRight,
  ChevronDown,
  RefreshCw,
  HardDrive,
} from "lucide-react";
import FileViewer from "./FileViewer";

interface FileItem {
  name: string;
  path: string;
  is_dir: boolean;
  size?: number;
  modified?: number;
  ext?: string;
}

interface FileExplorerProps {
  sessionId: string;
  className?: string;
}

const FILE_ICONS: Record<string, typeof File> = {
  ".py": FileCode,
  ".js": FileCode,
  ".ts": FileCode,
  ".tsx": FileCode,
  ".jsx": FileCode,
  ".html": FileCode,
  ".css": FileCode,
  ".json": FileCode,
  ".md": FileText,
  ".txt": FileText,
  ".pdf": FileText,
  ".doc": FileText,
  ".docx": FileText,
  ".ppt": FileImage,
  ".pptx": FileImage,
  ".png": FileImage,
  ".jpg": FileImage,
  ".jpeg": FileImage,
  ".gif": FileImage,
  ".svg": FileImage,
};

function getFileIcon(item: FileItem) {
  if (item.is_dir) return Folder;
  return FILE_ICONS[item.ext || ""] || File;
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function formatTime(ts: number): string {
  const d = new Date(ts * 1000);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export default function FileExplorer({ sessionId, className = "" }: FileExplorerProps) {
  const [files, setFiles] = useState<FileItem[]>([]);
  const [currentPath, setCurrentPath] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [expanded, setExpanded] = useState(true);
  const [viewingFile, setViewingFile] = useState<string | null>(null);

  const loadFiles = useCallback(async () => {
    if (!sessionId) return;
    setLoading(true);
    setError("");
    try {
      const params = currentPath ? `?path=${encodeURIComponent(currentPath)}` : "";
      const resp = await fetch(`/api/sessions/${sessionId}/files${params}`);
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
      const data = await resp.json();
      setFiles(data.files || []);
    } catch (e: any) {
      setError(e.message);
      setFiles([]);
    } finally {
      setLoading(false);
    }
  }, [sessionId, currentPath]);

  useEffect(() => {
    loadFiles();
  }, [loadFiles]);

  // Auto-refresh every 5 seconds
  useEffect(() => {
    const timer = setInterval(loadFiles, 5000);
    return () => clearInterval(timer);
  }, [loadFiles]);

  const navigateTo = (item: FileItem) => {
    if (item.is_dir) {
      setCurrentPath(item.path);
    }
  };

  const navigateUp = () => {
    if (!currentPath) return;
    const parts = currentPath.split("/").filter(Boolean);
    parts.pop();
    setCurrentPath(parts.join("/"));
  };

  const downloadFile = (item: FileItem) => {
    const url = `/api/sessions/${sessionId}/files/${encodeURIComponent(item.path)}`;
    const a = document.createElement("a");
    a.href = url;
    a.download = item.name;
    a.click();
  };

  const openInNewTab = (item: FileItem) => {
    const url = `/api/sessions/${sessionId}/files/${encodeURIComponent(item.path)}`;
    window.open(url, "_blank");
  };

  const viewFile = (item: FileItem) => {
    setViewingFile(item.path);
  };

  const pathParts = currentPath.split("/").filter(Boolean);

  return (
    <div className={`flex flex-col ${className}`}>
      {/* Header */}
      <div
        className="flex items-center justify-between px-3 py-2 cursor-pointer hover:bg-[var(--surface-hover)] rounded-lg transition-colors"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-center gap-2 text-sm font-medium" style={{ color: "var(--text-primary)" }}>
          <HardDrive size={15} />
          <span>工作区文件</span>
          {!expanded && files.length > 0 && (
            <span
              className="text-[10px] px-1.5 py-0.5 rounded-full"
              style={{ background: "var(--surface-hover)", color: "var(--text-secondary)" }}
            >
              {files.length}
            </span>
          )}
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={(e) => {
              e.stopPropagation();
              loadFiles();
            }}
            className="p-1 rounded hover:bg-[var(--surface-hover)] transition-colors"
            style={{ color: "var(--text-secondary)" }}
            title="刷新"
          >
            <RefreshCw size={13} className={loading ? "animate-spin" : ""} />
          </button>
          {expanded ? (
            <ChevronDown size={14} style={{ color: "var(--text-secondary)" }} />
          ) : (
            <ChevronRight size={14} style={{ color: "var(--text-secondary)" }} />
          )}
        </div>
      </div>

      {/* Content */}
      {expanded && (
        <div className="mt-1 flex-1 overflow-y-auto min-h-0" style={{ maxHeight: "400px" }}>
          {/* Breadcrumb */}
          {currentPath && (
            <div className="flex items-center gap-1 px-3 py-1 text-xs" style={{ color: "var(--text-secondary)" }}>
              <button onClick={() => setCurrentPath("")} className="hover:underline hover:text-violet-400">
                root
              </button>
              {pathParts.map((part, i) => (
                <span key={i} className="flex items-center gap-1">
                  <span>/</span>
                  <button
                    onClick={() => setCurrentPath(pathParts.slice(0, i + 1).join("/"))}
                    className="hover:underline hover:text-violet-400"
                  >
                    {part}
                  </button>
                </span>
              ))}
            </div>
          )}

          {/* Up button */}
          {currentPath && (
            <button
              onClick={navigateUp}
              className="w-full flex items-center gap-2 px-3 py-1.5 text-xs rounded-md hover:bg-[var(--surface-hover)] transition-colors"
              style={{ color: "var(--text-secondary)" }}
            >
              <Folder size={14} />
              <span>..</span>
            </button>
          )}

          {/* Error */}
          {error && (
            <div className="px-3 py-2 text-xs text-red-400">{error}</div>
          )}

          {/* Empty */}
          {!loading && !error && files.length === 0 && (
            <div className="px-3 py-4 text-center text-xs" style={{ color: "var(--text-secondary)" }}>
              暂无文件
            </div>
          )}

          {/* File list */}
          {files.map((item) => {
            const Icon = getFileIcon(item);
            const isOpenable =
              [".md", ".txt", ".json", ".html", ".css", ".js", ".ts", ".tsx", ".jsx",
               ".py", ".svg", ".go", ".rs", ".java", ".sql", ".yaml", ".yml",
               ".sh", ".bash", ".xml", ".c", ".cpp", ".h", ".hpp", ".r", ".rb", ".php",
               ".vue", ".svelte", ".toml", ".ini", ".cfg", ".conf", ".log", ".csv",
               ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp",
               ".dockerfile", ".makefile", ".env", ".gitignore",
              ].includes(item.ext || "");

            return (
              <div
                key={item.path}
                className="group flex items-center gap-2 px-3 py-1.5 text-xs rounded-md hover:bg-[var(--surface-hover)] transition-colors cursor-pointer"
                onClick={() => (item.is_dir ? navigateTo(item) : (isOpenable ? viewFile(item) : downloadFile(item)))}
              >
                <Icon
                  size={14}
                  className={item.is_dir ? "text-amber-400" : "text-violet-400"}
                  style={item.is_dir ? {} : { color: "var(--text-secondary)" }}
                />
                <span className="flex-1 truncate" style={{ color: "var(--text-primary)" }}>
                  {item.name}
                </span>
                {!item.is_dir && (
                  <span className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    {item.size !== undefined && (
                      <span style={{ color: "var(--text-secondary)" }}>{formatSize(item.size)}</span>
                    )}
                    {isOpenable && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          viewFile(item);
                        }}
                        className="px-1.5 py-0.5 rounded text-[10px] bg-violet-500/20 text-violet-400 hover:bg-violet-500/30"
                      >
                        查看
                      </button>
                    )}
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        downloadFile(item);
                      }}
                      className="p-0.5 rounded hover:bg-violet-500/20"
                      style={{ color: "var(--text-secondary)" }}
                    >
                      <Download size={12} />
                    </button>
                  </span>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* File viewer modal */}
      {viewingFile && (
        <FileViewer
          sessionId={sessionId}
          filePath={viewingFile}
          onClose={() => setViewingFile(null)}
        />
      )}
    </div>
  );
}
